version: '3.3'

services:
    node:
        image: $NODE_IMAGE
        volumes:
            - ./..:/app
        command: bash -c 'yarn && yarn start'
        working_dir: /app
        ports:
            - '8080:8080'
        restart: unless-stopped
